server.port=8081
spring.datasource.url=jdbc:sqlite:tag-dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.mapper-locations=mapper/*.xml

spring.jackson.deserialization.UNWRAP_ROOT_VALUE=false
