server.port=8082
spring.datasource.url=jdbc:sqlite:/data/article.db
spring.datasource.driver-class-name=org.sqlite.JDBC
user-service.url=http://user-service:8081
jwt.secret=nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
jwt.sessionTime=86400
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=mapper/*.xml
