server.port=8085
spring.application.name=tag-service

spring.datasource.url=jdbc:sqlite:tag-service.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.tagservice.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
