plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':shared-lib')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.xerial:sqlite-jdbc:3.36.0.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:2.2.2'
}
