spring.datasource.url=jdbc:sqlite:/app/data/user.db

user-service.url=http://user-service:8081
article-service.url=http://article-service:8082
comment-service.url=http://comment-service:8083
favorite-service.url=http://favorite-service:8084
