server.port=8084

spring.datasource.url=jdbc:sqlite:favorite.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.mapper-locations=mapper/*.xml

logging.level.io.spring.infrastructure.mybatis.mapper=DEBUG
