server.port=8083
spring.datasource.url=jdbc:sqlite:/data/comment.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jackson.deserialization.UNWRAP_ROOT_VALUE=true

jwt.secret=${JWT_SECRET}
jwt.sessionTime=${JWT_SESSION_TIME:86400}

user-service.url=http://localhost:8081
article-service.url=http://localhost:8082

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.commentservice.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml
