server.port=8081
spring.datasource.url=jdbc:sqlite:/data/user.db
spring.datasource.driver-class-name=org.sqlite.JDBC
jwt.secret=nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
jwt.sessionTime=86400
image.default=https://api.realworld.io/images/smiley-cyrus.jpeg
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=mapper/*.xml
